### ISSUE TITLE
Distribution and source code policy🐀 

### ISSUE THREAD

**Issue by HausemasterIssue** [SimplyProgrammer/Minecraft-Deobfuscator3000#2]
why is it an exe file? shouldn't it be in javaaaaaa?

**Comment by Doogie13** [comment]
hello HausemasterIssue

**Comment by HausemasterIssue** [comment]
hi, sorry for calling you out on ares client github. i just needed some
help with gamesense strafe. gamesense default strafe does work on 2b2t, but
I took your advice about the speed setting and for some reason it dosent
make a difference. here's where i did it,
github.com/hausemasterissue/spidersense, you can try and help if u want :)

**Comment by SimplyProgrammer** [comment]
> why is it an exe file? shouldn't it be in javaaaaaa?

Hello, yes it indeed was .jar file for a while but I have decided to convert it into .exe
reason 1. I can add some additional information into .exe file (such as icon), .exe file is also crucial portability part!
reason 2. Is fact that .exe file is looking less scary than .jar file because most applications are .exe files (at least in my opinion ).
reason 3. Currently, Deobfuscator3000 should be downloaded from [https://drive.google.com/u/0/uc?export=download&confirm=H8-1&id=1rGNEUmifdM7jomaKo_O6nyKTTUBrHk7_](this link). This will download a setup that will download the application as any normal application and you can launch it using icon from your desktop!

**Comment by HausemasterIssue** [comment]
.exe is more scary than .jar tbh because .exe contain a lot more viruses
and are much harder to impossible i think to read the source code of.

just make it a .jar :)

**Comment by SimplyProgrammer** [comment]
well yeah, now I can see. You want a source code... but that is kind of exactly what I am trying to prevent. I never wanted this to be open source bcs like why you want to see my crappy source code after all. Just download it, install it and chill, that's what it was designed for :)! 
But if you like really really want to see it then listen... I don't know if you have noticed, judging from your question you did not but that exe file is nothing more than jar file in a mask so you should be able to extract or open it like any other jar file. And after this, basically all what you need to do is decompile it and you have source code.

**Comment by HausemasterIssue** [comment]
okay. it's just i don't want to run many closed source programs on my pc.
especially if they are from some random github (no offense). thanks, i will
do that :)

**Comment by SimplyProgrammer** [comment]
well, you are welcome!
I will consider making it open source but it will most likely result in license changes.
